DROP TABLE FISH_NAME_INFO ;
CREATE TABLE FISH_NAME_INFO (
	FISH_TYPE INTEGER NOT NULL PRIMARY KEY,
	FISH_NAME VARCHAR2(100) NOT NULL
);
DROP TABLE FISH_INFO ;
CREATE TABLE FISH_INFO (
	ID INTEGER NOT NULL PRIMARY KEY,
	FISH_TYPE INTEGER NOT NULL,
	LENGTH FLOAT,
	TIME DATE NOT NULL,
	CONSTRAINT FISH_TYPE_FK FOREIGN KEY (FISH_TYPE) REFERENCES FISH_NAME_INFO(FISH_TYPE)
);

--ALTER TABLE HR.FISH_INFO ADD CONSTRAINT
--FISH_INFO_FISH_NAME_INFO_FK FOREIGN KEY (FISH_TYPE) REFERENCES HR.FISH_NAME_INFO(FISH_TYPE);


