-- 데이터 삽입
-- INSERT
-- 테이블에 새로운 데이터 행을 추가할 때 사용한다.
-- INSERT INTO 테이블명 (컬럼명들) VALUES (값들)
SELECT *
FROM TBL_STUDENT;
-- 여러 행 삽입
-- INSERT ALL을 사용하여
-- 여러 줄을 동시에 삽입할 수 있다.
-- 마지막에 SELECT * FROM DUAL을 써주어야 한다.
INSERT ALL
	INTO TBL_STUDENT (STUDENT_ID, NAME, BIRTH_DAY)
	VALUES (8, '이길동', '2001-01-01')
	INTO TBL_STUDENT (STUDENT_ID, BIRTH_DAY)
	VALUES (9, '2002-01-01')
SELECT * FROM DUAL;
INSERT INTO TBL_STUDENT (STUDENT_ID, NAME, BIRTH_DAY)
VALUES (80, '이길동', '2001-01-01');
INSERT INTO TBL_STUDENT (STUDENT_ID, NAME, BIRTH_DAY)
VALUES (82, '이길동', '2001-01-01');


