-- 
SELECT *
FROM EMPLOYEES e ;

-- 문제1
/* EMPLOYEES 테이블에서
 * FIRST_NAME, LAST_NAME, JOB_ID를 출력하는데
 * SALARY를 오름차순으로 정렬하여 출력해보자.
 * */
SELECT FIRST_NAME , LAST_NAME , JOB_ID, SALARY ,
EMPLOYEE_ID 
FROM EMPLOYEES e 
ORDER BY SALARY ASC, EMPLOYEE_ID DESC;


