CREATE TABLE TBL_PRODUCT (
	PRODUCT_ID	NUMBER,
	CATEGORY 	VARCHAR2(100),
	RAW_PRICE	NUMBER NOT NULL,		
	SELL_PRICE	NUMBER,
	DC			NUMBER,
	STOCK		NUMBER,
--	제약조건 PK만들기
	CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_ID)
);

-- TBL_SHOPPING
CREATE TABLE TBL_SHOPPING (
	SHOPPING_ID NUMBER NOT NULL,
	PRODUCT_ID	NUMBER NOT NULL,
	PRICE		NUMBER	NOT NULL,
	COUNT		NUMBER	NOT NULL,
	CONSTRAINT	SHOPPING_PK PRIMARY KEY (SHOPPING_ID),
	CONSTRAINT	PRODUCT_ID_FK FOREIGN KEY (PRODUCT_ID) REFERENCES TBL_PRODUCT(PRODUCT_ID)
);


