-- 날짜와 시간 함수
-- SYSDATE
-- 시스템 시간(세계표준시UTC)를 반환한다(~밀리초)
SELECT SYSDATE 
FROM DUAL;

-- CURRENT_DATE
-- 컴퓨터에 기록되고 있는 시간을 반환한다.(~밀리초)
SELECT SYSDATE, CURRENT_DATE
FROM DUAL;

-- ADD_MONTHS
-- 주어진 날짜타입의 값에 특정 개월 수를 더하여
-- 미래 혹은 과거의 해당 날짜타입의 값을 반환한다.
SELECT TO_CHAR(D.TARGET, 'YY.MM.DD')
FROM (
	SELECT ADD_MONTHS(SYSDATE, (12 * 30 * 1.5)) AS TARGET
	FROM DUAL
) D;

-- TASK1
-- HIRE_DATE를 기준으로 12개월 뒤의 날짜를 새로운 열에 표현하는데,
-- 열 이름: 계약 만료 예정일
-- 2020-10-01 계약 만료 예정
SELECT FIRST_NAME, HIRE_DATE,
TO_CHAR(ADD_MONTHS(HIRE_DATE, 12), 'YYYY-MM-DD') AS "계약 만료 예정일"
FROM EMPLOYEES;

-- MONTHS_BETWEEN
-- 두 날짜타입의 데이터 사이의 정확한 개월 차이를 계산하여
-- 실수 값으로 반환하는 함수
SELECT ROUND(MONTHS_BETWEEN(SYSDATE, TO_DATE('2024-02-6', 'YYYY-MM-DD'))) AS "올해 몇월" 
FROM DUAL;

-- 사원의 ID와 HIRE_DATE
-- 매니저의 사원ID와 HIRE_DATE를 표현하는데,
-- 두 테이블을 JOIN, ON 사원.MANAGER_ID = 매니저.EMP_ID
SELECT E.EMPLOYEE_ID 사원번호,
TO_CHAR(E.HIRE_DATE, 'YYYY-MM-DD') 사원입사일,
M.EMPLOYEE_ID 매니저번호,
TO_CHAR(M.HIRE_DATE, 'YYYY-MM-DD') 매니저입사일
, ROUND(MONTHS_BETWEEN(E.HIRE_DATE, M.HIRE_DATE)) AS "입사 간격"
, (E.HIRE_DATE - M.HIRE_DATE) AS "입사간격(일)"
, (TO_NUMBER(TO_CHAR(E.HIRE_DATE, 'YYYY')) - TO_NUMBER(TO_CHAR(M.HIRE_DATE, 'YYYY'))) AS "입사간격(연)"
FROM EMPLOYEES E
JOIN EMPLOYEES M
ON E.MANAGER_ID = M.EMPLOYEE_ID;






SELECT E.EMPLOYEE_ID "사원번호",
E.HIRE_DATE,
M.EMPLOYEE_ID "매니저번호",
M.HIRE_DATE,
ROUND(MONTHS_BETWEEN(E.HIRE_DATE, M.HIRE_DATE))
FROM EMPLOYEES E
JOIN (
	SELECT EMPLOYEE_ID, HIRE_DATE
	FROM EMPLOYEES E2
) M
ON E.MANAGER_ID = M.EMPLOYEE_ID
;


SELECT EMPLOYEE_ID, MANAGER_ID, HIRE_DATE 
FROM EMPLOYEES e
ORDER BY HIRE_DATE DESC
;



SELECT BIRTH_DATE 
FROM PLAYER p
WHERE BIRTH_DATE IS NOT NULL
ORDER BY BIRTH_DATE DESC
;



