-- UNION
-- 두 개 이상의 SELECT 문의 결과를 하나의 테이블로
-- 합쳐서 중복된 결과값은 제거하는 합집합의 역할을 하는 명령어
-- 주의할 점: 두 SELECT문의 SELECT할 컬럼은 개수와 대상이 같아야 한다.
SELECT FIRST_NAME, EMPLOYEE_ID, DEPARTMENT_ID 
FROM EMPLOYEES E
WHERE DEPARTMENT_ID = 90
UNION 
SELECT FIRST_NAME, EMPLOYEE_ID, DEPARTMENT_ID 
FROM EMPLOYEES M
WHERE M.SALARY > 10000
ORDER BY FIRST_NAME; 

SELECT FIRST_NAME , EMPLOYEE_ID , DEPARTMENT_ID 
FROM EMPLOYEES e 
WHERE DEPARTMENT_ID = 90
OR SALARY > 10000
ORDER BY FIRST_NAME 
;

-- MINUS
-- 첫번째 테이블에서는 존재하지만 두번째 테이블에는 없는
-- 행을 반환한다.
-- -> 첫번째 테이블에서 두 테이블의 공통된 행을 제거한 결과를 반환
SELECT SALARY
FROM EMPLOYEES E
WHERE SALARY > 10000
--ORDER BY SALARY 
MINUS
SELECT SALARY
FROM EMPLOYEES E2
WHERE E2.SALARY > 17000
ORDER BY SALARY DESC;






