CREATE TABLE TBL_FLOWER (
	 FLOWER_ID NUMBER NOT NULL PRIMARY KEY,
	 FLOWER_NAME VARCHAR2(100) NOT NULL,
	 FLOWER_PRICE NUMBER
--	 CONSTRAINT FLOWER_PK PRIMARY KEY (FLOWER_ID)
);

CREATE TABLE TBL_POT (
	POT_ID NUMBER NOT NULL PRIMARY KEY,
	POT_NAME VARCHAR2(100) NOT NULL,
	POT_PRICE NUMBER
--	CONSTRAINT POT_PK PRIMARY KEY (POT_ID)
);

CREATE TABLE TBL_PRODUCT (
	PRODUCT_ID NUMBER NOT NULL PRIMARY KEY,
	FLOWER_ID NUMBER NOT NULL,
	POT_ID NUMBER NOT NULL,
	PRICE NUMBER
--	제약 조건 PK, FK
	-- PK
--	CONSTRAINT PRODUCT_PK PRIMARY KEY (PRODUCT_ID),
--	CONSTRAINT FLOWER_FK FOREIGN KEY (FLOWER_ID) REFERENCES TBL_FLOWER(FLOWER_ID),
--	CONSTRAINT POT_FK FOREIGN KEY (POT_ID) REFERENCES TBL_POT(POT_ID)
);

ALTER TABLE TBL_FLOWER
ADD CONSTRAINT PK_FLOWER PRIMARY KEY (FLOWER_ID);

ALTER TABLE TBL_PRODUCT
ADD CONSTRAINT FK_FLOWER FOREIGN KEY (FLOWER_ID)
REFERENCES TBL_FLOWER(FLOWER_ID);

ALTER TABLE TBL_PRODUCT 
ADD CONSTRAINT FK_POT FOREIGN KEY (POT_ID)
REFERENCES TBL_POT(POT_ID);

-- 가격은 0원 이상이어야 한다
-- CHECK (조건식)
ALTER TABLE TBL_PRODUCT 
ADD CONSTRAINT CHK_PRICE CHECK (PRICE >= 0);

-- 조건 삭제
ALTER TABLE TBL_PRODUCT 
DROP CONSTRAINT CHK_PRICE;

-- PK 삭제
ALTER TABLE TBL_PRODUCT 
DROP PRIMARY KEY;

-- PK 추가
ALTER TABLE TBL_PRODUCT 
ADD CONSTRAINT PRODUCT_PK PRIMARY KEY (FLOWER_ID, POT_ID);






