CREATE TABLE TBL_COSTOMER (
	COSTOMER_ID NUMBER PRIMARY KEY,
	NAME VARCHAR2(100),
	EMAIL VARCHAR2(100) UNIQUE,
	ADDRESS VARCHAR2(100)
);

CREATE TABLE TBL_ORDER (
	ORDER_ID NUMBER PRIMARY KEY,
	ORDER_DATE DATE DEFAULT SYSDATE,
	PRICE NUMBER NOT NULL,
	COSTOMER_ID NUMBER,
	CONSTRAINT CONSTOMER_FK FOREIGN KEY (COSTOMER_ID) REFERENCES TBL_COSTOMER(COSTOMER_ID) 
);
DROP TABLE TBL_ORDER;






